### ISSUE TITLE
modernize: createRef API, functional components with hooks

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-react-examples#3]
We should modernize these examples based on React 16.9. A couple basic things to do:

- migrate to function components with useState hook: https://reactjs.org/docs/hooks-state.html
- migrate to createRef API: https://reactjs.org/docs/refs-and-the-dom.html#refs-and-function-components

**Comment by bryik** [comment]
[An attempt](https://github.com/bryik/mapbox-react-examples/tree/basic-hooks). IMO it would be better to add a [`basic-with-hooks`](https://github.com/bryik/mapbox-react-examples/blob/basic-hooks/basic/src/index.js) example rather than update every example to use hooks. Perhaps I'm just not comfortable enough with hooks yet, but the class examples feel more approachable 🤷‍♂️

Notes:

- Using a prop as a default value in an initialization hook seems to require [wrapping in useRef()](https://github.com/bryik/mapbox-react-examples/blob/basic-hooks/data-overlay-redux/src/components/map.js#L15)?
- There is probably a way to do the [tooltip example](https://github.com/bryik/mapbox-react-examples/tree/basic-hooks/react-tooltip) with [portals](https://reactjs.org/docs/portals.html)--didn't look too far into it.

Dan Abramov has an interesting post about ["Making setInterval Declarative with React Hooks"](https://overreacted.io/making-setinterval-declarative-with-react-hooks/); perhaps mapbox-gl-js could be made more declarative with custom hooks for initializing a map, updating mapStyle...

**Comment by tshddx** [comment]
@bryik Finding this was very helpful! I initially went down the path of trying to use `const map = React.useMemo(...)` for a few minutes before I checked the internet and found this, and of course you're right that we need to `useState` instead because we need to have the map container ref.

**Comment by justincy** [comment]
Here's my take on hooks with mapbox-gl: https://dev.to/justincy/using-mapbox-gl-in-react-d2n

**Comment by astridx** [comment]
[Another attempt for the basic and the tooltip example](https://github.com/astridx/mapbox-react-examples/tree/test).

**Comment by tristen** [comment]
Closed by #11!
